### ISSUE TITLE
lint skip uses_setuptools

### ISSUE THREAD

**Issue by sebastian-luna-valero** [bioconda/bioconda-utils#108]
Hello,

I am trying to skip an unnecessary test here:
https://travis-ci.org/CGATOxford/bioconda-recipes/jobs/231235853#L602

by using ` [lint skip uses_setuptools for recipes/cgat-pipelines-nosetests]` in the commit message but it does not seem to work.

Could you please help?

Best regards,
Sebastian

**Comment by bgruening** [comment]
@sebastian-luna-valero can you try: `[lint skip uses_setuptools for cgat-pipelines-nosetests]`

**Comment by johanneskoester** [comment]
@sebastian-luna-valero, what do you mean with unnecessary?

**Comment by sebastian-luna-valero** [comment]
Thanks Both.

@johanneskoester I am following the instructions here:
https://bioconda.github.io/linting.html#skipping-a-linting-test

where `setuptools` is listed in a meta-package, causing the test to fail. However, I am sure I need it.

@bgruening with your suggestion I get a new issue:
https://travis-ci.org/CGATOxford/bioconda-recipes/jobs/231290615#L512

**Comment by sebastian-luna-valero** [comment]
Hi!

Following up on this, do you know why `bioconda_utils` is planning to build also recipes other than mine?
https://travis-ci.org/CGATOxford/bioconda-recipes/jobs/232339054#L511

Best regards,
Sebastian

**Comment by johanneskoester** [comment]
I guess this is because your fork was merged with upstream/master? This way, you get new commits changing those recipes. If they have not yet been uploaded (because they are currently building), travis can't know what to do else. This does not happen when you create a pull request, because then we use the diff to the master branch and see that those recipes did not change at all.

**Comment by sebastian-luna-valero** [comment]
You're right, many thanks!
