### ISSUE TITLE
Channel priority: [bioconda, conda-forge] or [conda-forge, bioconda]

### ISSUE THREAD

**Issue by mbargull** [bioconda/bioconda-utils#330]
@bioconda/core: What do you think about changing the channel priority (as suggested in the docs and used for the CI) from
```
- bioconda
- conda-forge
- defaults
```
to
```
- conda-forge
- bioconda
- defaults
```
? We actively try to avoid (via linter checks in Bioconda as well as conda-forge) name clashes between different packages in both channels. Hence the cases where we have packages with the same name in both channels are usually when we have outdated version of packages in `bioconda` for which newer versions are now maintained in `conda-forge`. Due to `conda`'s channel priority we then express a preference for the older version in `bioconda` if that channel has higher priority. This is usually not what the user would expect and also something that puts excessive load on the dependency solver, e.g.,
trying to run
```
conda create -nenv -c bioconda -c conda-forge qualimap=2.2.2a=3
```
takes 14 hours or so, while
```
conda create -nenv -c conda-forge -c bioconda qualimap=2.2.2a=3
```
finishes in seconds. Plus, `-c bioconda -c conda-forge qualimap=2.2.2a=3` will give you the old `r=3.3.2` (due to outdated R packages in `bioconda`) which is also probably not what a user would expect.

Personally, I'm very much in favor of changing the channel priority and don't see much benefit in having `bioconda` on top. What do think?

----
latest refs:

----
@abalter in https://github.com/conda/conda/issues/7646#issuecomment-418315927: 
> @mbargull -- you made [this suggestion](https://github.com/conda/conda/issues/7684#issuecomment-415588307) on a different issue I raised, and it solved the problem. It also solved other problems I was having with building environments with `bioconda` bioconductor packages. I should probably raise the issue with bioconda.
> 
> > The current state of the Bioconda docs still says to give bioconda the higher priority. In reality (due to the issue you just encountered) in often makes sense to use
> ```
> channels:
>   - conda-forge
>   - bioconda
>   - defaults
> ```
> >though. (defaults has to be in the mix because conda-forge is not yet self-contained and depends on packages only available in defaults.)

----
@mbargull in https://github.com/conda/conda/issues/7684#issuecomment-415588307:
> > @mbargull does work on both projects so I'm pinging him in-case he has some advice.
> 
> Thanks for the ping. It's true that this is a Bioconda-specific thing. So, the gist is that for historical reasons there are outdated R packages in `bioconda` with newer versions/builds of those being available in `conda-forge` and by giving `bioconda` the highest channel priority, we are forcing `conda` to strongly prefer those outdated builds. In your case those outdated R 3.3.2 packages probably depend on `readline 6.*` but didn't specify that constraint and thus don't work with `readline 7.0` being installed.
> So, there are some pros and cons to putting `bioconda` before `conda-forge` or the other way around. The current state of the Bioconda docs still says to give `bioconda` the higher priority. In reality (due to the issue you just encountered) in often makes sense to use
> ```
> channels:
>   - conda-forge
>   - bioconda
>   - defaults
> ```
> though. (`defaults` has to be in the mix because `conda-forge` is not yet self-contained and depends on packages only available in `defaults`.) 

----

**Comment by bgruening** [comment]
You have my full support! 

> Personally, I'm very much in favor of changing the channel priority and don't see much benefit in having bioconda on top. What do think?

The argument against this was raised by @johanneskoester afaik and it was that we have no change to overrule a package that is in conda-forge with one that is in bioconda.

@johanneskoester is that still a valid concern?

**Comment by mbargull** [comment]
We should also keep in mind that future `conda` version will likely offer to set a (non-default!) `strict` channel priority, see:
https://github.com/conda/conda/issues/7656, https://github.com/conda/conda/pull/7660, and https://github.com/conda/conda/pull/7729.
If it's implemented as currently suggested and enabled, then those old versions in `bioconda` will likely lead to many non-satisfiable environments.
On the other hand it will also mean that if `conda-forge` has top priority, this mean that those packages in `bioconda` are completely ignored for `strict` channel priority.

But note that `strict` will not be the default, but can have many benefits in regard to conflicts between `conda-forge` and `defaults` -- something that also affects `bioconda`.

**Comment by mbargull** [comment]
> The argument against this was raised by @johanneskoester afaik and it was that we have no change to overrule a package that is in conda-forge with one that is in bioconda.
> 
> @johanneskoester is that still a valid concern?

I think it is still a valid concern :grin:! But in my opinion it just heavily outweighed by problems it is causing.

**Comment by ocefpaf** [comment]
> The argument against this was raised by @johanneskoester afaik and it was that we have no change to overrule a package that is in conda-forge with one that is in bioconda.

I'm glad I bumped in this issue and I would like to say two things about this comment:

- `conda-forge` just created a "sub-team" item on its governance and we welcomed a `bioconda` and or `R` sub-team to help us solve any issue for that particular community quicker. See https://conda-forge.org/docs/subgroups/index.html for more info.

-  If I got the concern right wouldn't the pin package syntax `bioconda::packageX` suffice to overrule a particular package? (Of course that can become a nuisance if there are many packages.)

**Comment by rvalieris** [comment]
to be honest I was already using conda-forge as the top priority channel for a while now, for similar reasons you mention, so no objection from me.

**Comment by bgruening** [comment]
So let's do it?

**Comment by epruesse** [comment]
In favor.

Although its *counter intuitive* to layer Bioconda underneath Conda-Forge instead of on top, it does make sense:  The legacy packages in Bioconda are superseded by those in Conda-Forge.

@ocefpaf It would be good to have a mechanism in Conda-Forge that guards against accidental name space conflicts. Perhaps requiring `extra: override_sister_channel: bioconda` in the recipe to add a feedstock for a name already occupied by Bioconda. 

There are packages for which these things are ambiguous. For example, the package name `arb` refers to  the arbitrary precision math library [arblib](http://arblib.org) in Redhat based distros. In Debian based distros `arb` installs the phylogenetic sequence analysis suite [ARB](http://arb-home.de). In Conda-Forge `arb` installs `libarb`, so in Bioconda I gave in to necessity and chose `arb-bio` as package name for the tool `arb` to avoid conflict. Not ideal or intuitive for the end-user, but first-come-first-serve is the only way to maintain reproducibility.

**Comment by johanneskoester** [comment]
These are only historical packages that are now in conda-forge that cause the problems, right? Couldn't we simply move those packages to bioconda-legacy? Then we could maintain the old order, which seems more intuitive, and to which people are used now.

**Comment by epruesse** [comment]
Removing packages **breaks** reproducibility.

Whether *removing* is achieved by moving packages to `bioconda-legacy`, or whether it's assigning labels other than `main` as done in Conda-Forge -- taking things out of the channel creates pain and breakage. We need to avoid that.

That's why I'm in favor of changing the order. We can just have the Conda-Forge packages supersede the legacy Bioconda ones.

But that's also why we need a linter to protect against name space clashes.

A governance team can only **react** to a problem once it has already happened, often enough way too late. The linter can **prevent** it from happening. If some kind of "override" flag in the `meta.yaml` is required to create a package that is already in *the other channel*, then we can at least be sure that the recipe author and the reviewers are acting in awareness of the namespace conflict.

**Comment by johanneskoester** [comment]
Yeah, I know @epruesse. My rationale was that (a) it should happen only this one time, and not anymore in the future, and (b) we could ensure that the same version is available in conda-forge as well. However, thinking about it, it is probably not clear whether this might happen in the future again, e.g., because non-bio packages are added to bioconda accidentally. Inverting the priority might scale better in the future, since a package is automatically chosen from conda-forge once it is present there. Hence, less trouble in maintenance. So, yeah, you have my ok to do this.

**Comment by nsoranzo** [comment]
Close?

**Comment by janxkoci** [comment]
As end user, should I now change the channel order in all my older installations? And instruct all my colleagues to do the same?

**Comment by dpryan79** [comment]
@janxkoci Yes, please do.
