### ISSUE TITLE
Add `conda update --all` to installation instructions

### ISSUE THREAD

**Issue by scientificbruno** [bioconda/bioconda-utils#450]
May I suggest that `conda update --all` is added to the channel setup instructions on the [Bioconda homepage](https://bioconda.github.io/). This would minimize the risk of users running into binary incompatibility. This just happened to me with the default `readline` package and the `r` package after a fresh Miniconda install. 

You can close this issue if you don't like the idea. I just wanted to share some feedback to help future Bioconda users. Cheers!

**Comment by epruesse** [comment]
What's the status on this? I think it got lost. Do we want to suggest the `update --all` considering the problems with the solver?

**Comment by dpryan79** [comment]
I strongly suggest not doing this, since it implies that people are installing gobs of packages in their root environments (this is likely VERY common already). We should really encourage people to make copious use of environments (they can then just make a fresh env rather than updating stuff). I also worry that `conda update --all` will ignore pinnings of non-updated packages in the same way that `conda install` seems to.

**Comment by bgruening** [comment]
I agree with @dpryan79. In 2019 this should not be needed anymore and we really should use environments and touch the `base` environment as less as possible.

**Comment by epruesse** [comment]
>  I also worry that conda update --all will ignore pinnings of non-updated packages in the same way that conda install seems to.

`conda install` ignores pins of things that aren't updated? That can't be possible. Sounds like a corner-case bug to me. Really?

**Comment by dpryan79** [comment]
> conda install ignores pins of things that aren't updated?

Yes, there were countless people complaining about `samtools` breaking because they were using `conda install` to add something to an environment that had samtools and openssl was upgraded beyond what pinning allowed. I suspect this is particular to openssl, since it's set to be aggressively upgraded, but still.

**Comment by epruesse** [comment]
It could be specific to the openssl package, actually. The legacy versioning scheme doesn't fit the pythonic Conda `VersionOrder`.

**Comment by dpryan79** [comment]
I suspect it's more to do with it being listed under `conda config --show aggressive_update_packages`.

**Comment by epruesse** [comment]
Still... scary
