### ISSUE TITLE
Bot: rerun CI jobs failing due to bad gateway

### ISSUE THREAD

**Issue by epruesse** [bioconda/bioconda-utils#463]
This kind of problem here:

```
conda.exceptions.CondaHTTPError: HTTP 502 BAD GATEWAY for url <https://conda.anaconda.org/bioconda/noarch/repodata.json>
```

**Comment by epruesse** [comment]
This would be a check for circleci logs triggered by the check_suite failed event we should get once the build has finished with errors.

**Comment by epruesse** [comment]
Could be something to handle from `utils.run` actually. Just retry the command 3 times if the log contains  `CondaHTTPError: HTTP 504 GATEWAY_TIMEOUT for url <https://conda.anaconda.org/bioconda/linux-64/repodata.json>`

**Comment by mbargull** [comment]
This will hopefully be mitigated with https://github.com/bioconda/bioconda-recipes/issues/13832.

Nonetheless, if it's something on the `conda`-side (e.g., fetching `repodata`, not uploading to `anaconda.org` etc.), we can let `conda` handle this, at least partially:

<details open><summary><code>
conda config --describe
</code></summary>

```
[...]

# ######################################################                                                                                                                                                                                                                          
# ##              Network Configuration               ##                                                                                                                                                                                                                          
# ######################################################                                                                                                                                                                                                                         

[...]

# # local_repodata_ttl (bool, int)                                        
# #   For a value of False or 0, always fetch remote repodata (HTTP 304
# #   responses respected). For a value of True or 1, respect the HTTP
# #   Cache-Control max-age header. Any other positive integer values is the
# #   number of seconds to locally cache repodata before checking the remote
# #   server for an update.                              
# #                                                     
# local_repodata_ttl: 1                                 

[...]

# # remote_connect_timeout_secs (float)
# #   The number seconds conda will wait for your client to establish a     
# #   connection to a remote url resource.
# #
# remote_connect_timeout_secs: 9.15
                                         
# # remote_max_retries (int)             
# #   The maximum number of retries each HTTP connection should attempt.
# #                                                     
# remote_max_retries: 3                                 
                                                             
# # remote_read_timeout_secs (float)
# #   Once conda has connected to a remote resource and sent an HTTP
# #   request, the read timeout is the number of seconds conda will wait for
# #   the server to send a response.                                
# #                                                                      
# remote_read_timeout_secs: 60.0                                          

[...]
```

We could increase the `remote_*` parameters generally, if that helps.
If you think a general increase is not desirable and -- for whatever reason -- only the `repodata` fetching is error-prone, we could also increase the `remote_*` params only temporarily while fetching that index and increase `local_repodata_ttl` to something bigger than the CI build time, so it doesn't get re-fetched.

**Comment by epruesse** [comment]
What does the Cache-Control max-age say on anaconda? I'd say upping the local_repodata_ttl to 100000 for the builds is ok. No need to re-pull that. It doubt the chance for that changing in the middle of the run was considered by anyone anyway.

Another thought is to have `utils.RepoData` write out the `repodata.json` once it's downloaded it. I've yet to see our own downloader fail.

**Comment by epruesse** [comment]
Looks like `conda.core.subdir_data` is the place. Wish those were documented APIs and not meddling with internal things.

**Comment by mbargull** [comment]
> What does the Cache-Control max-age say on anaconda?

From (last year's) memory: Depends on the channel. `defaults` channels have a couple of seconds, things already at `conda-static.anaconda.org`, i.e., now `conda-forge` (only `main` label AFAIC), should have 20 minutes, and everything else from `conda.anaconda.org` (i.e. `conda-web.anaconda.org`) none at all.

>  write out the `repodata.json` once it's downloaded

> Looks like `conda.core.subdir_data` is the place.

Externally downloading and injecting into `conda`'s cache? Oh no, no good idea. Things like `conda.core.subdir_data.cache_fn_url` and such are veerry far from public API and should not not be considered stable at all :laughing:. Only ever use things provided by the CLI or exposed via `conda.exports`. Anything else is better left alone :wink:.

> I've yet to see our own downloader fail.

Interesting... So you're saying that empirically it looks like `conda` itself is less reliable in fetching `repodata.json` files than `bioconda-utils` itself? Quite peculiar!

**Comment by mbargull** [comment]
```
~ >>>  curl -sI https://repo.anaconda.com/pkgs/main/noarch/repodata.json | grep cache-control || echo NONE                                                                                       
cache-control: public, max-age=30
~ >>>  curl -sI https://conda.anaconda.org/conda-forge/noarch/repodata.json.bz2 | grep cache-control || echo NONE                                                                                
cache-control: public, max-age=1200
~ >>>  curl -sI https://conda-static.anaconda.org/conda-forge/noarch/repodata.json.bz2 | grep cache-control || echo NONE                                                                         
cache-control: public, max-age=1200
~ >>>  curl -sI https://conda-web.anaconda.org/conda-forge/noarch/repodata.json.bz2 | grep cache-control || echo NONE                                                                            
NONE
~ >>>  curl -sI https://conda.anaconda.org/conda-forge/label/cf201901/noarch/repodata.json.bz2 | grep cache-control || echo NONE                                                                 
NONE
~ >>>  curl -sI https://conda.anaconda.org/bioconda/noarch/repodata.json.bz2 | grep cache-control || echo NONE                                                                    
NONE
```

**Comment by epruesse** [comment]
> > What does the Cache-Control max-age say on anaconda?

So looks like no caching for bioconda, eventually 20 minutes once we are on CDN. We should use the ttl settings anyhow to put this to an hour.

> Externally downloading and injecting into `conda`'s cache? Oh no, no good idea. Things like `conda.core.subdir_data.cache_fn_url` and such are veerry far from public API and should not not be considered stable at all laughing. Only ever use things provided by the CLI or exposed via `conda.exports`. Anything else is better left alone wink.

Not sure if it makes a difference whether it's public API or not. You don't want me to go on a rant about `conda_build.api` and `conda.exports`. Suffice to say that something calling itself  "API" should not fail with `sys.exit`, but provide suitable exception classes, should not use `print`, but `logging`, etc.

That said - no, I don't like the idea much either. It's why we have our own `RepoData` object in the first place. Accessing *any* of conda's API, though, means adding unit tests to check it's still doing what we think it is and accepting that it will break at some point in the future.

> > I've yet to see our own downloader fail.
> 
> Interesting... So you're saying that empirically it looks like `conda` itself is less reliable in fetching `repodata.json` files than `bioconda-utils` itself? Quite peculiar!

Not really. It's design. Conda does blocking IO, we do not.

Basically, `conda` downloads each file consecutively, retrying without wait up to three times and waiting for new data blocks up to 10 seconds. For 9 files, if one gets stalled, that can take quite a while and will fail more often. (They use `requests` in their own complicated `gateway` layer abstracing from http/ftp/s3).

`bioconda-utils` downloads all files at the same time. Because the wait for an individual file does not impact everything, timeouts can be higher. Retry time is increased via a fibonacci series. (We use `aiohttp`, `aioftp`, `aiofiles` and `backoff` to get a proper `/dev/epoll` state machine suitable for a web crawler courtesy of Python 3 asyncio).

I've reused code for this I had written for `YMP` to have the environment install process take a more reasonable time. For that, I download files into a cache of my own and then call `conda install` on the tar balls. Much much faster, and doesn't constantly stall/fail when you try to install a dozen environments at once.

The whole asyncio business was necessary for `autobump`. Can't call out to hundreds of webservers to scan for package updates and wait for each of them to respond before you can go on. Also, we need to honor API rate limiting etc. That just doesn't work well with sync IO. E.g. the bot now has constant streams open receiving messages from Gitter, while listening to webhooks from github and circle, scheduling background tasks and doing REST API calls. Threads might have been an alternative, but they aren't very efficient in Python and awkward to code for.

**Comment by mbargull** [comment]
> You don't want me to go on a rant about `conda_build.api` and `conda.exports`.

For `conda.exports`, please do! That's something I can surely help with :wink:.
`conda-build` is an entirely different beast, though. I'll gladly take a pass on that :laughing:.

> Not really. It's design. Conda does blocking IO, we do not.

Ah, I see. I haven't looked at `bioconda-utils` for a long time. Glad to hear we are `async` ^^!

<details><summary>
off-topic, regarding conda:
</summary>

Yes, there are a bunch of abstractions all over the place. Some are helping, others make things more cumbersome. Plus, there are not few things that need overhauling. One big hindrance is that they still support PY2 (for `conda` itself that is), which is a PITA and I can't even imagine how many thousands of $$$ have been wasted because of it. As a `conda` contributor, my No. 1 feature request for `conda 5` is ( = has been for a looong time) to drop PY2 support and move `conda` itself out of the `base` into its very own env! A couple of years back @soapy1 did some work on that in https://github.com/conda/conda/pull/3988 ... She's back on the dev team... So... Maybe.. One can only dream ^^ <sub>(or bribe? Hi Sophia :smile:, just let me know how you and your bosses are bribable :stuck_out_tongue_winking_eye: .)</sub>
</details>

Thanks for all the details, much appreciated! I hope I'll soon(-ish) be able to check out all the work you have done on `bioconda-utils` and also `YMP` -- sounds interesting!

**Comment by epruesse** [comment]
<details><summary>off-topic, regarding conda:</summary>

> For conda.exports, please do!

> Things like conda.core.subdir_data.cache_fn_url and such are veerry far from public API 

`from conda.exports import cache_fn_url` :smiling_imp: 

Some docs would be good. There is  [`conda.api`](https://docs.conda.io/projects/conda/en/latest/api/index.html), but I can find nothing on  `conda.exports`. It seems to be an ad-hoc collection. It also seems fragile - how do you know when messing about in `conda.core.subdir_data` that `cache_fn_url` is semi-public API?

Also, thread safety, a comprehensive API, write access to things like the package cache for client code, clean logging and error handling, good documentation, etc (always performance as well, of course). YMP and Snakemake also have to jump through a bunch of hoops to manage environments for the user. It's necessary though, so that "micro envs" can be used avoiding all the problems with larger envs. Wish I could just fork of a bunch of threads each saying "make an env from this spec and call it xyz". Alas, I can't.
</details>

**Comment by mbargull** [comment]
<details><summary>
off-topic, regarding conda:
</summary>

> `from conda.exports import cache_fn_url` :smiling_imp:

Goddammit! I did some `git blame`-ing and it looks like that went in due to a request for some legacy stuff at Anaconda (https://github.com/conda/conda/issues/4247). \*sigh\*, well it is what it is... I assumed it wasn't public, but apparently you are "free to use it". Though, I still wouldn't necessarily advice on doing that since there has been talk on changing the `repodata` caching, i.e., if you build things on it now, you could be forced to revise that in a couple of months.

But yes, docs/explanations for `conda.exports` would be good. You are right regarding the "ad-hoc" style: a long while ago `conda-build` was part of `conda` itself and hence used `conda`'s non-public stuff. When `conda-build` got separated, it still used all that non-public stuff; obviously problematic. So at some point `conda.exports` was created to collect all things `conda-build` (as well as some other software at ContinuumIO) needed access to. Ergo: Yes, it's a semi-random dump of `conda`-functionality and not a proper API at all. But at least it has been maintained and has been stable enough by now for `conda-build`, various conda-forge software, `bioconda-utils`, etc. (Not to say that a proper API would be good to have -- but don't hold your horses on that. I don't think `conda.api` is being actively worked on (would be pleasantly surprised otherwise).)
Well, I guess it would make sense to go through all of those exports in `conda.export`, check for/add proper docs for that and sort/tier them w.r.t. to their domain/usefulness/stability.

> thread safety

\*grml\* That's a tough one. Most (nearly all?) of `conda` has been done without that in mind. Hence this needs a overhaul/rewrite of most of the code. So while I agree it's desirable, I'm sure it won't happen soon. Maybe we can start improving it here and there, starting with the index and package caches.

> a comprehensive API

Yeah, see the above.

> write access to things like the package cache for client code

Hm.. I think this is probably not going to happen anytime soon. Maybe somewhere down the line when `conda` gets more modular/composable. Currently, `conda`'s inner workings can be a little intertwined and thus might assume some conditions/invariants and hence not handle external interference well. No idea when this will be improved upon.

> clean logging and error handling

A couple years back I on that a bit to clean that up and make `conda` behave better when used as a library. There were still some things left to do in that regard, IIRC. But I have no idea if it regressed and how the current status is on that. If you can identify any concrete issues, please don't hesitate to open an issue for that and ping me on it.

> good documentation

I saw (but didn't really check out) that there has been done some work on the user docs in the last couple months, which is nice to see. If you have any particular topics you think should be added/improved, just open an issue on `conda`'s issue tracker (the docs live in that repository now).

> always performance as well, of course

I hope to be able to work (or the very least advice) on that :smile:.

I took some notes on your requests, thanks for the feedback!
</details>

**Comment by epruesse** [comment]
CDN has fixed this.
