### ISSUE TITLE
Disable issues on bioconda-recipes

### ISSUE THREAD

**Issue by epruesse** [bioconda/bioconda-utils#489]
From #454:
> Issues on bioconda-recipes: disable them?

I assume the reason for the idea is that we have chaos over there and no-one to take care of it.

**Comment by chapmanb** [comment]
I agree that there are too many issues for any of us to triage successfully, but we need a place for people to report and help with issues. My suggestions:

- Provide a guideline for submitting issues, ideally having submitters tag the package maintainers by looking at a package history. I often miss bugs because I'm not actively watching recipe issues.
- Setup a tagging system for issues so we can separate build issues from install issues from package-specific issues.
- Try to recruit community members to do issue triage and help with the sorting and tagging.

**Comment by epruesse** [comment]
My thoughts were similar. Using `issue templates`, `labels` and the `bot` we can mechanize some of the triaging, but we would need the manpower to deal with the tickets, too.

**Comment by tomkinsc** [comment]
Yes, I had similar thoughts as well. We should keep issues, but guide reporters a bit more in how they should be used.

**Comment by HenningTimm** [comment]
I just learned that github offers project boards (various flavors of partially automated Kanban boards) to organize Issues, PRs, etc., which could be helpful for triaging issues. The [remacs project](https://github.com/remacs/remacs/projects) is using them for both bug tracking and managing work packages.

This might help to to categorize issues based on the tagging system, since it allows filtered views on subsets of issues (e.g. all build issues).

**Comment by epruesse** [comment]
Closing. We aren't going to disable the issues.
