### ISSUE TITLE
Blast latest version

### ISSUE THREAD

**Issue by MichWeb75** [bioconda/bioconda-utils#649]
Dear Bioconda-Team,

I want to install NCBI BLAST Tools with
`conda install -c bioconda blast`

it offers blast=2.5 and numpy

However when I 
`conda install -c bioconda blast=2.9`

offers blast 2.9, Entrez-Direct and Perl 5.26`

My question: Why conda does not choose the latest version. And second why do versions have different dependencies even though blast itself has actually no dependencies ?

**Comment by dpryan79** [comment]
The blast suite does have dependencies for some tools, which is why perl is installed. Regarding the version you get, `conda install` will try to best match the versions available to whatever is compatible with the environment you're in. For this reason you are strongly encouraged to create new environments, such as `conda create -n new_blast -c conda-forge -c bioconda blast`, which will install the most recent version of blast that we ship. Note also that you'll want to have conda-forge as the highest priority channel, since bioconda dependencies come from there.
