### ISSUE TITLE
Making mulled-build optional

### ISSUE THREAD

**Issue by yesimon** [bioconda/bioconda-utils#68]
I was trying to build an OS X package and running `simulate-travis.py` ended up failing due to trying to perform a `mulled-build`. Since I don't need mulled build functionality, is it possible to make `mulled-build` optional per package? We can still have it be true by default but have an optional to turn it off.

**Comment by tomkinsc** [comment]
I'd love to have the ability to opt out of container-based build/test, to avoid scenarios like [this one](https://github.com/bioconda/bioconda-recipes/pull/3531) where insufficient space is available to build larger packages due to container overhead or fs constraints. The earlier bioconda build system that built directly on Travis was ideal IMHO, and it would be wonderful to have the ability to choose that path, if we want to distribute a conda package but not a mulled container. Building for mulled is a sensible default, but having an option to opt-out is valuable for bioconda's future. Otherwise we risk losing packages to other channels with more flexible build systems.

**Comment by bgruening** [comment]
@yesimon mulled-build is part of our quality control pipeline. If mulled-build is failing there is usually something from with your package. Very common error is that zlib is missing, or some X-libs ... maybe even libgcc. The generation of containers is just a positive site-effect.

@tomkinsc please write to Travis to get more storage space. They are very friendly! We can get more space by default if needed or we just wait until they increase the limit by default (should happen in the next months).

**Comment by johanneskoester** [comment]
Milled has two aspects. The first is the container itself. This is minor to me. The second is the quality control. It tests the package in an environment without any system libraries. However I can also understand the if not everybody is happy with it, since it does not work in each scenatio. What about disabling mulled in the normal builds and having a chron job that generates the containers each night?

**Comment by bgruening** [comment]
What I care about is the quality control, if we allow to skip these, we loosening our testing .. we should instead foster more testing. Besides the space limitation, I haven't seen any valid error that was false positive - and the space issue can also probably be fixed by removing the tarballs (conda clean) after the normal conda build is done.

For the feels like an excuse to skip a useful test, instead of fixing the package or the test.

**Comment by yesimon** [comment]
We're already building our Linux packages within a docker container, so I don't see how we're gaining additional quality control by creating a docker container out of the package. Regardless, I would love to see it become a separate process because certainly not all packages need a mulled build.

**Comment by mvdbeek** [comment]
> What about disabling mulled in the normal builds and having a chron job that generates the containers each night?

That's going to accumulate broken (in the sense that some things will be linked against dependencies provided by travis) packages in bioconda and a nice backlog of containers that will never build. I strongly hope that's not the direction this project goes.
I understand though that it's madness to do this on the Travis infrastructure, especially as the number of contributors increases. I'd be able and willing to donate some cloud resources, if someones is willing to write a nice Jenkins abstraction.

**Comment by johanneskoester** [comment]
@mvdbeek There would be no linking against Travis dependencies since we build in a docker container.

The mulled container (based on BusyBox) just has even less libs installed than the docker container used for building. However, I think we maybe  should be able to tune our build container to be similar to mulled. If that works, mulled could go into a chron job.

**Comment by bgruening** [comment]
@yesimon a little bit of history that might make it more obvious. One year back, we were building in a Docker container that had zlib and many other packages installed. What happend is that more or less no package had a zlib dependency. We changes that and made it more strict by removing zlib from the container for example. Now your recipe fails if you do not have zlib installed - I would argue this is a good thing for the bioconda community.

Now, we can not remove everything out of the build-container, es the conda environment needs to be there as a basic minimum. So we developed an approach that tests a bioconda package in a busybox - where nothing is installed. This is the *only* currently we can ensure that the build and test environment are separated.

It's fine that you create your own container, but this is not my point. We use this container for strict testing - and obviously your container is broken in some (the stric) way.

**Comment by bgruening** [comment]
> The mulled container (based on BusyBox) just has even less libs installed than the docker container used for building. However, I think we maybe  should be able to tune our build container to be similar to mulled. If that works, mulled could go into a chron job.

Yes this could work. But I don't think this is easily possible, you still need to have conda available and you don't share the same build environment as with conda-forge. Not sure how important that nowadays is.

**Comment by johanneskoester** [comment]
The question would be how self-contained Miniconda3 is. Does it need anything from the system? Would it run in busybox?

In fact, there is also a third way to achieve the quality control of mulled, without mulled:
```
usage: conda-inspect linkages [-h] [--untracked] [--show-files]
                              [--groupby {package,dependency}] [--all]
                              [-n ENVIRONMENT | -p PATH]
                              [packages [packages ...]]

Investigates linkages of binary libraries in a package (works in Linux and
OS X). This is an advanced command to aid building packages that link against
C libraries. Aggregates the output of ldd (on Linux) and otool -L (on OS X) by
dependent packages. Useful for finding broken links, or links against system
libraries that ought to be dependent conda packages.  

Options:

positional arguments:
  packages              Conda packages to inspect.

optional arguments:
  -h, --help            Show this help message and exit.
  --untracked           Inspect the untracked files in the environment. This
                        is useful when used in conjunction with conda build
                        --build-only.
  --show-files          Show the files in the package that link to each
                        library
  --groupby {package,dependency}
                        Attribute to group by (default: package). Useful when
                        used in conjunction with --all.
  --all                 Generate a report for all packages in the environment.
  -n ENVIRONMENT, --name ENVIRONMENT
                        Name of environment (in /home/johannes/.local/opt/mini
                        conda/envs:/home/johannes/.conda/envs).
  -p PATH, --prefix PATH
                        Full path to environment prefix (default:
                        /home/johannes/.local/opt/miniconda).
```
What do you think?

**Comment by yesimon** [comment]
@bgruening Yes I remember the zlib issues and removing it from the container is the right approach.

The quality control comes from revealing all dependencies that are implicitly in the build container but are actually required for the program, so ideally we would have separate build and test containers. However mulled is not the ideal test container because most packages are not developed against busybox! (even though this doesn't matter for the vast vast majority of cases). 

As stated above, conda-inspect should be able to achieve the quality control of a test container without having to utilize a test container.

**Comment by bgruening** [comment]
@johanneskoester we tried that and it didn't worked reliable for all cases. As soon as you mix build and test environment you can not be 100% sure about a functioning package. What is better than testing a package in a clean environment.

> most packages are not developed against busybox!

And they are developed against what? What is the target you want to develop against? Busybox is simply the most strict thing I can imaging. Btw. we can change the runtime environment in mulled in theory, for example we can include xlib - then all packages will not work without xlib.

Can we please try to fix your package and not discussing ways around it?

**Comment by tomkinsc** [comment]
@bgruening: Removing cached package tarballs via `conda clean -a -y` after a build but before testing is sensible. How can we best implement that? Is it something we can and should do as a standard part of our build process? (I vote yes) I'm mostly impartial to container-based builds if they are approximately as capable as the host system.

**Comment by bgruening** [comment]
Seriously, this is working since 4 month now for 600 packages, I don't see why we should relax our testing here :( :-1: 

@tomkinsc in bioconda-utils, we just need to find the correct spot to do this.

**Comment by yesimon** [comment]
I will assert without proof that most people are running bioinformatics without using docker containers. In this case, unless they are running their bioinformatics pipelines on Alpine Linux or Android, they most likely are based off GNU/Linux which busybox linux utilities definitely cannot feature match on. This can become a problem for any package that executes a linux utility. 

Regardless of whether or not it works fine, I don't see why I need to extend the time of my build-test cycle for a use case that I will never ever use. Building and distributing a conda package != building and distributing a mulled package. They are two logically separate steps.

**Comment by mvdbeek** [comment]
> I will assert without proof that most people are running bioinformatics without using docker containers. In this case, unless they are running their bioinformatics pipelines on Alpine Linux or Android, they most likely are based off GNU/Linux which busybox linux utilities definitely cannot feature match on. This can become a problem for any package that executes a linux utility.

So then include the piece of software that busybox is lacking as a dependency in your conda package and be sure that it runs everywhere. If that thing is so commonplace I have a hard time imagining that is is many GB large and would slow down the build.


> Regardless of whether or not it works fine, I don't see why I need to extend the time of my build-test cycle

If you want a short build test cycle, you could just test things locally with simulate-travis.py. I think the value in bioconda is that you can be fairly confident that the packages here work, and for that the important thing is isolated testing. And more testing is never wrong.

**Comment by bgruening** [comment]
> I will assert without proof that most people are running bioinformatics without using docker containers.

It's not about containers here, it's about conda package quality.

> In this case, unless they are running their bioinformatics pipelines on Alpine Linux or Android, they most likely are based off GNU/Linux which busybox linux utilities definitely cannot feature match on. This can become a problem for any package that executes a linux utility. 

Exactly and we try to solve this problem why simply don't assume anything, like zlib that many upstream packages assume - that the reason we need to patch nearly all makefile to make this work.

> Regardless of whether or not it works fine, I don't see why I need to extend the time of my build-test cycle 

You are arguing about the 5min that this additional test takes?
Just to let you know I have contacted Traivs twice to enlarge our max build-time to 2h ... not because of mulled, but that we can build bigger or more complicated packages. Not because I need it but because the community needs it.

If you don't see a benefit in spending these additional minutes, maybe you see a benefit to produce high quality packages for people other then you, that might have different needs? I would call this community :) 

> for a use case that I will never ever use. 

You maybe not, but maybe others :).

> Building and distributing a conda package != building and distributing a mulled package. They are two logically separate steps.

This is a testing feature in first place, you can also argue that we should do less testing in other places to get you personally to a faster build. I think we are going the opposite direction, e.g. with this PR: https://github.com/bioconda/bioconda-utils/pull/57 and make our packages even more robust in the future.

**Comment by yesimon** [comment]
@mvdbeek My original point was that `simulate-travis.py` performs a `mulled-build`. I'm not even sure why this is happening on OS X (probably a mistake), but we definitely need the option to toggle it there.

On one hand you want something that "just works", but for whom? It's not unreasonable to expect GNU/Linux, so much so that people just call it "Linux" nowadays. The rabbit hole can keep getting deeper. What about different versions of linux utilities, and what about glibc? Shouldn't these in theory also be specified with their versions in the requirements? You can ensure greater and greater isolation from a host system at higher and higher cost for the packager.

**Comment by mvdbeek** [comment]
A commandline switch to simulate-travis.py wouldn't be too bad, as long as there's no way to merge a PR that turns it off.

**Comment by bgruening** [comment]
@yesimon can you make sure BIOCONDA_UTILS_ARGS does not container mulled-test as here: https://github.com/bioconda/bioconda-recipes/blob/master/.travis.yml#L16

**Comment by tomkinsc** [comment]
@mvdbeek: The script`simulate-travis.py` is only used locally, so having a command line switch available in that script to disable mulled build locally is immaterial to any travis testing or PR merges.

**Comment by johanneskoester** [comment]
@yesimon apart from whatever will come out of this thread, it would be very interesting to see what exactly fails in your case.

**Comment by mvdbeek** [comment]
https://github.com/bioconda/bioconda-recipes/blob/master/scripts/travis-setup.sh#L30
But yeah, you can control this by setting BIOCONDA_UTILS_ARGS.

**Comment by epruesse** [comment]
`simulate-travis.py` has been replaced. Using `bioconda-utils build`, `--mulled-test` is now optional.
