### ISSUE TITLE
Current extended-base (`quay.io/bioconda/base-glibc-debian-bash:3.0`) for container builds yields docker images unusable on some systems

### ISSUE THREAD

**Issue by pontus** [bioconda/bioconda-utils#958]
Since docker 25.0.0 (https://docs.docker.com/engine/release-notes/25.0/#2500), 

* Unpacking layers with extended attributes onto an incompatible filesystem will now fail instead of silently discarding extended attributes. [moby/moby#45464](https://github.com/moby/moby/pull/45464)

The current image used as extended-base for container images unfortunately has one such extended attribute (`user.overlay.impure`) set for /etc/ (set to `y`). 

This breaks various setups. In some cases it can be worked around (e.g. changing docker storage driver to `overlay-fuse` instead of `overlay2`), but it causes problems for users (and some situations, e.g. gitpod, make it quite difficult).

Since I can't this being actually used anywhere, maybe we can use a base image without such an extended attribute?

**Comment by daler** [comment]
@pontus the base image is built using [this Dockerfile](https://github.com/bioconda/bioconda-containers/blob/main/images/base-glibc-debian-bash/Dockerfile). We're in the middle of moving the image-building over into this repo (bioconda-utils), but that dockerfile is not changing.

The building itself is happening [here](https://github.com/bioconda/bioconda-containers/blob/main/.github/workflows/base-glibc-debian-bash.yaml) with podman/buildah. That is currently being unified with other image building to happen here in bioconda-utils, but the commands are not changing.

It's not immediately clear to me where the issue is being introduced, whether in the dockerfile, buildah commands, or later on when creating containers with mulled/involucro. Based on the links above is there anything you see that might be causing the issue?

**Comment by pontus** [comment]
Thanks, I don't see anything that sticks out to me and can't directly replicate this when I try locally, I'll try to play a bit with that in github actions and see if I can trigger it.

**Comment by ewels** [comment]
Sounds promising, thanks @ChristopherHX! Link to PR for others: https://github.com/containers/storage/pull/1847 (took me a while to find because I didn't realise that `containers/storage` was an actual repo name at first 😅 )

**Comment by pontus** [comment]
Hrrm, I haven't yet been able to trigger this issue with buildah, and the commit there is large enough that I can't read it and figure out how to trigger it either.

**Comment by pontus** [comment]
> See [containers/storage#1847](https://github.com/containers/storage/pull/1847) for how to reproduce this by pulling an image built by buildah using latest docker:dind-rootless image. My host system can apply that xattr without an error using a rootful docker 25.x version.

Yes, I've seen the issue, I just haven't been able to trigger the issue (being the built image having a that extended attribute somewhere) myself with buildah.

**Comment by pontus** [comment]
Thanks. I haven't managed to produce anything with these xattrs (and the above example does not) with Ubuntu 23.10 and buildah installed from standard sources with apt.
